baseURL: https://billyfryer.com
languageCode: en
theme: hugo-apero
title: Billy Fryer's Website
author: Billy Fryer
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 6
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: Billy Fryer's Website
  favicon: /img/schs logo.png
  headingFontFamily: sans-serif
  logo: /img/schs logo.png
  mainSections:
    - blog
    - project
    - visualizations
    - wbb
    - contact
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/Reynolds.jpg
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/billyfryer/
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/BillyFryer42
    - icon: linkedin-in
      icon_pack: fab
      url: https://www.linkedin.com/in/billy-fryer/
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: plum
  twitter: apreshill
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: hugo-apero/apero
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
  header:
    - name: About
      title: About Me
      url: /about/
      weight: 1
    - name: Projects
      title: Project Portfolio
      url: /projects/
      weight: 2
    - name: Visualizations
      title: Visualizations Portfolio
      url: /visualizations/
      weight: 3
    - name: Women's Basketball
      title: Women's Basketball Analysis
      url: /wbb/
      weight: 4
    - name: Contact
      title: Contact Form
      url: /contact/
      weight: 5
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
